package com.mycompany.mavenproject1.ui;

import com.mycompany.mavenproject1.business.CountryBusiness;
import com.mycompany.mavenproject1.data.Country;
import javax.swing.JOptionPane;

public class CountryUI extends javax.swing.JFrame {

    private CountryBusiness countryBusiness;
    
    public CountryUI() {
        initComponents();
    }

    CountryUI(CountryBusiness countryBusiness) {
        this();
        
        this.countryBusiness = countryBusiness;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createbt = new javax.swing.JButton();
        listbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        namelb = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        acronlb = new javax.swing.JLabel();
        acrontxt = new javax.swing.JTextField();
        phonedigitslb = new javax.swing.JLabel();
        phonedigitstxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listarea = new javax.swing.JTextArea();

        setTitle("Country Management");
        setPreferredSize(new java.awt.Dimension(500, 250));

        createbt.setText("Create");
        createbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtActionPerformed(evt);
            }
        });
        jPanel1.add(createbt);

        listbt.setText("List");
        listbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listbtActionPerformed(evt);
            }
        });
        jPanel1.add(listbt);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        namelb.setText("Name");
        jPanel2.add(namelb);
        jPanel2.add(nametxt);

        acronlb.setText("Acronym");
        jPanel2.add(acronlb);
        jPanel2.add(acrontxt);

        phonedigitslb.setText("Phone Digits");
        jPanel2.add(phonedigitslb);
        jPanel2.add(phonedigitstxt);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        listarea.setColumns(20);
        listarea.setRows(5);
        jScrollPane1.setViewportView(listarea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listbtActionPerformed
        listarea.setText(countryBusiness.readAll().toString());
    }//GEN-LAST:event_listbtActionPerformed

    private void createbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtActionPerformed
        
        Country c = new Country();
        
        c.setName( nametxt.getText());
        c.setAcronym(acrontxt.getText());
        c.setDigits(new Integer(phonedigitstxt.getText()));
        
        try {
            countryBusiness.create(c);
            
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_createbtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acronlb;
    private javax.swing.JTextField acrontxt;
    private javax.swing.JButton createbt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listarea;
    private javax.swing.JButton listbt;
    private javax.swing.JLabel namelb;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel phonedigitslb;
    private javax.swing.JTextField phonedigitstxt;
    // End of variables declaration//GEN-END:variables
}
